CHANGELOG.md, composer.json, src/assets/class-manifest.php, src/assets/interface-manifest-data.php, src/class-main.php
- Added dependency injection in service locator inside class-main.php
- Changed Manifest.php method to fetch items to non static method.
- Updating Manifest.php with new methods
=> Implementing Dependency injection

.gitattributes, .gitignore, CHANGELOG.md, README.md, composer.json, documentation/README.md, documentation/features/blocks.md, documentation/features/columns.md, documentation/features/custom-post-type.md, documentation/features/custom-taxonomy.md, documentation/features/enqueue.md, documentation/features/general.md, documentation/features/i18n.md, documentation/features/intro.md, documentation/features/login.md, documentation/features/manifest.md, documentation/features/media.md, documentation/features/menu.md, documentation/features/rest.md, documentation/helpers/general-helpers.md, documentation/helpers/object-helpers.md, documentation/index.md, documentation/installation/instalation-and-requirements.md, package-lock.json, package.json, src/columns/class-base-post-columns.php, src/columns/class-base-taxonomy-columns.php, src/columns/class-base-user-columns.php, src/exception/class-plugin-activation-failure.php
- Added docpress documentation.
- Updating readme
- class-base-post-columns.php - New abstract class for adding articles listing columns.
- class-base-taxonomy-columns.php - New abstract class for adding taxonomy listing columns.
- class-base-user-columns.php - New abstract class for adding users listing columns.
- class-plugin-activation-failure.php - New plugin activation exception.
- Updating min php version to 7.1
=> adding documentation

CHANGELOG.md, src/exception/class-missing-template.php, src/helpers/class-components.php
Changelog
---
* Added `class-components.php` helper for using components in WordPress views and other components
Part of https://github.com/infinum/eightshift-frontend-libs/pull/83
=> Add components helper class.

CHANGELOG.md, src/helpers/class-components.php
Changelog
---
* Added ability to wrap components with parent class on render
=> Add parent wrapper attribute.

CHANGELOG.md, src/enqueue/class-assets.php, src/enqueue/class-enqueue-admin.php, src/enqueue/class-enqueue-blocks.php, src/enqueue/class-enqueue-theme.php
This build was seriously broken.
- There was a method missing in enqueue classes.
=> Fixing enqueue classes for missing method

src/custom-post-type/class-label-generator.php
Replaced the project text domain
=> Fix the wrong text-domain

.travis.yml, composer.json, phpcs.xml.dist, src/blocks/class-blocks.php, src/class-main.php, src/exception/class-component-exception.php, src/exception/class-invalid-manifest.php, src/has-activation-interface.php, src/has-deactivation-interface.php, src/helpers/class-components.php, src/manifest/class-manifest.php
Added a low-level JSON parse to detect `manifest.json` errors, such as trailing commas and such.
Not sure what since tag should be added 🤷‍♂️
=> Add manifest json validation

CHANGELOG.md, src/helpers/class-components.php
=> adding responsive-selector-helper

CHANGELOG.md, src/class-main.php
=> Made the prepare method more flat

.github/workflows/ci.yml, bin/lintPhp.sh, composer.json, composer.lock, phpstan.neon.dist
I've added the CI workflow (GH Actions), also added `phpstan`, and made some minor modifications to `composer.json`.
I've also upped the PHP version requirement to 7.2
=> Add GitHub actions

CHANGELOG.md, src/blocks/class-blocks.php
- `class-blocks.php` - removed normal blocks view and made wrapper view as default.
- `class-blocks.php` - removed hasWrapper key.
- `class-components.php` - changes on `responsive_selectors` method because of a bug in rendering bool.
=> updating blocks

src/helpers/class-components.php
* Components:render helper was not working in Plugin Boilerplate setup
=> updating helper

eightshift-projects/bin/build.sh, eightshift-projects/bin/deploy.sh
Related to #69 
Stop the execution of the build and deploy scripts on error.
=> Stop the script on error

codeception.yml, composer.json, src/Main/AbstractMain.php, src/Main/Autowiring.php, tests/_output/.gitignore
Working implementation of autowiring for both interfaces and classes (+ Codeception unit tests setup). 🎉 
What it does
---
* It automatically builds definition lists for dependencies for all services and other classes which have dependencies. (This means no more manually adding classes to `class-main.php`)
* It injects class-based dependencies
* It injects interface-based dependencies based on variable name. How? It will look through all psr-4 compliant classes and try to find exactly 1 by matching the dependency variable name to classname (and seeing if that class implements the desired interface). If it finds 0 or 2+ classes, it will just skip it and you'll have to manually define dependencies for that class.
* Services are automatically put on the definition list and then registered as …
=> Autowiring

src/class-main.php
Please see https://github.com/infinum/eightshift-libs/pull/90/checks?check_run_id=1305354674 and https://github.com/infinum/eightshift-libs/search?q=instantiate_service
=> Remove unused *private* instantiate_service method

.github/workflows/ci.yml
Work is being done in `develop`!
=> Don't let develop test-less

src/Blocks/AbstractBlocks.php, src/Blocks/BlocksExample.php, src/CustomMeta/AbstractAcfMeta.php, src/Enqueue/Admin/AbstractEnqueueAdmin.php, src/LintPhp/LintPhpCli.php, src/Login/AbstractLogin.php, src/Rest/Fields/AbstractField.php, src/Rest/Routes/AbstractRoute.php, src/ThemeOptions/ThemeOptionsExample.php
Also, added some fixes in ACF based classes and in the linter.
=> Fix callback params

src/Helpers/Components.php
Rename BEM selector methods and docblocks
=> Rename BEM selector methods

src/View/AbstractEscapedView.php
Allow `selected` attribute to the `option` element
Allow `checked` and `disabled` attribute to the `input` element
=> Update form allowed html list

src/I18n/I18nExample.php
- fixing hook priority in order for the languages to work in themes
=> updating language priority

src/Config/AbstractConfigData.php, src/Config/ConfigCli.php, src/Config/ConfigDataInterface.php, src/Config/ConfigExample.php, src/ConfigProject/ConfigProjectCli.php, src/ConfigProject/ConfigProjectExample.php, src/ModifyAdminAppearance/ModifyAdminAppearanceExample.php
- switching to native ways for env handler
- removing never used methods because we are using imposter and we don't need to prefix our stuff
=> updating env handler

phpstan.neon.dist
=> Fix WP-CLI's autoload mess

src/Blocks/AbstractBlocks.php
Fix last PHPStan error.
Please see #124
=> Improve array processing in AbstractBlocks

composer.json
Please see https://getcomposer.org/doc/04-schema.md#version
and all popular packages.
=> Composer version should be omitted

src/Blocks/BlocksExample.php
Adde Reusable block by default in the admin sidemenu.
Related to this PR https://github.com/infinum/eightshift-docs/pull/74/files
=> adding reusable blocks

src/Helpers/Post.php
Created a helper that can be added in a single post to measure the time it takes to read it (approximately).
The unit test will be written in pest in the 3.1.0 update.
=> Add reading time helper

.github/workflows/ci.yml, .github/workflows/test.yml
- run only on pushes/PR-s to develop branch
- YAML strings
- execute `composer update`
- ~~explicit Composer options~~ got a 👎
=> Improve CI

tests/Enqueue/Blocks/EnqueueBlockCliTest.php, tests/Enqueue/Blocks/EnqueueBlockExampleTest.php, tests/data/public/manifest.json
Writing tests for Enqueue Blocks. 
Issue:
#121
=> Enqueue Blocks tests

src/Blocks/BlockCli.php, src/Helpers/Components.php, tests/Blocks/BlocksCliTest.php, tests/ConfigProject/ConfigProjectCliTest.php
- Config project
- helpers Components
- blocks
=> updating tests

tests/Manifest/ManifestCliTest.php, tests/Manifest/ManifestExampleTest.php
My first tests, please be gentle :)
=> Manifest tests

src/Helpers/Components.php
@dingo-d 👀 See diff without whitespace changes: https://github.com/infinum/eightshift-libs/pull/164/files?diff=unified&w=1
=> Fix return+else by bailing out early

CHANGELOG.md, package.json, src/Main/Autowiring.php
This is a bugfix release that fixes the autowiring issue (exclude the non service classes).
Tested on a fresh project, no errors found.
=> 3.0.6 release

src/Build/BuildCli.php, tests/Build/BuildCliTest.php
=> BuildCli tests

tests/Columns/PostTypeColumnsTest.php, tests/Columns/TaxonomyColumnsTest.php, tests/Columns/UsersColumnsTest.php
Added tests for
- Post Type columns
- Taxonomy columns
- User columns
=> Add tests for the custom columns

.github/workflows/ci.yml, .github/workflows/test.yml
This should trigger checks on all PRs
=> Trigger checks on all PRs

src/Helpers/Components.php, tests/Helpers/ComponentHelpersTest.php, tests/data/src/Blocks/components/button/manifest.json, tests/data/src/Blocks/components/typography/manifest.json, tests/data/src/Blocks/custom/heading/manifest.json
adding options to convert css variable output to color, select-variable, boolean-variable and default. also option to add any css variable no mater the manifest
=> updating helper for css variables

tests/Blocks/BlocksExampleTest.php
One test outputted the contents out and the assertion was faulty so I fixed this.
=> Fix faulty test

src/Helpers/Components.php, tests/Datasets/Arguments.php, tests/Helpers/ComponentHelpersTest.php, tests/data/src/Blocks/components/typography/manifest.json
- updating css variables helper
=> updating variables helper

src/Cli/CliHelpers.php, src/Db/ImportCli.php, src/Helpers/Components.php, src/Setup/UpdateCli.php, tests/Helpers/ComponentHelpersTest.php, tests/data/src/Blocks/components/heading/manifest.json, tests/data/src/Blocks/components/typography/manifest.json
- updating manifest layout for custom variable key
- new helper to map responsive attributes in single array
=> updating new helper

src/Helpers/Components.php, tests/Helpers/ComponentHelpersTest.php, tests/data/src/Blocks/components/typography/manifest.json
- the same as on frontend libs.
- escaping outputs
=> updating responsive-select

src/Helpers/Components.php, tests/Helpers/ComponentHelpersTest.php, tests/data/src/Blocks/components/typography/manifest.json, tests/data/src/Blocks/components/variables/manifest.json
at this point just don't ask why
=> updating variables

src/Helpers/Components.php
Eightshift-libs fix of https://github.com/infinum/eightshift-frontend-libs/pull/363
=> Props renaming fix

src/Blocks/AbstractBlocks.php, src/Helpers/Components.php, tests/Helpers/ComponentHelpersTest.php
=> updating fixes to props

src/Helpers/Components.php, tests/Helpers/ComponentHelpersTest.php, tests/data/src/Blocks/components/responsiveVariables/manifest.json
Changelog:
- added responsive variables handler and its helper functions
PHP part of https://github.com/infinum/eightshift-frontend-libs/pull/362
Works basically the same.
Functions are named the same and function basically the same.
=> Responsive variables

src/Blocks/AbstractBlocks.php, src/Blocks/BlocksExample.php, src/Exception/InvalidBlock.php, src/Helpers/Components.php
Fixing helpers for new setup
- updating block registration
- props helper
- output css variables helper
Tests will fail because @IvanGrginovInf will update them once all tests on JS  are done
=> updating block registration and helpers for new props prefixes

src/Blocks/AbstractBlocks.php, src/Helpers/Post.php, tests/Helpers/PostHelperTest.php
Fixed phpstan and test failures. Once this is merged the #215 can be rebased so that the checks are passing.
=> Fix ci checks

composer.json, src/AdminMenus/AdminMenuCli.php, src/Helpers/Components.php, tests/AdminMenus/AdminMenuCliTest.php
Fixed some phpstan issues so that the blocks don't scream too much - they'll still scream because of some false positives and how some code is written (especially the `checkAttr` helper that returns everything so it's next to impossible to ensure type safety 😬).
=> Additional phpstan fixes

src/Helpers/Components.php
Same fix as https://github.com/infinum/eightshift-libs/pull/228 but for `checkAttrResponsive`
=> Fix check attr responsive phpstan issues

src/AdminMenus/AbstractAdminMenu.php, src/AdminMenus/AbstractAdminSubMenu.php, src/AdminMenus/AdminMenuCli.php, src/AdminMenus/AdminMenuExample.php, src/AdminMenus/AdminSubMenuCli.php, src/AdminMenus/AdminSubMenuExample.php
Admin menu and submenu fixes regarding typos on packages
=> Fix admin menu and submenu strings and packages

src/Blocks/AbstractBlocks.php, src/Blocks/BlocksExample.php, src/Cli/CliInitProject.php, src/Enqueue/Admin/AbstractEnqueueAdmin.php, src/Helpers/Components.php, tests/Blocks/BlocksExampleTest.php, tests/Enqueue/Admin/EnqueueAdminExampleTest.php
Used if we have a default paragraph block in the editor.
=> Add a filter for rendering block data

src/Main/AbstractMain.php, tests/Main/AbstractMainTest.php, tests/data/src/ThirdMockServiceClass.php
This PR will add a compiled container to the production or staging if the environment is set.
https://php-di.org/doc/performances.html
=> Compile DI container if environment is set to prod or staging

src/Helpers/Components.php, tests/Helpers/ComponentHelpersTest.php
Proposed fix related to issue #237. More detailed description is in mentioned issue.
=> Transform first letter of new key to uppercase

src/Main/AbstractMain.php, tests/Main/AbstractMainTest.php
the problem occurred if you had 2 libs in the project.
=> adding fix for di cache

.gitignore, src/Cli/Cli.php, src/CliCommands/AbstractCustomCommand.php, src/CliCommands/CustomCommandCli.php, src/CliCommands/CustomCommandExample.php, tests/Cli/CliTest.php, tests/CliCommands/CustomCommandExampleTest.php, tests/CliCommands/CustomCommandTest.php
Add WP CLI command to generate custom CLI command in project 
https://user-images.githubusercontent.com/47175420/147069665-60bc12e9-faf9-4835-9cfc-033472464699.mp4
=> Add Cli command to create custom cli commands

src/Blocks/AbstractBlocks.php, src/Menu/AbstractMenu.php, tests/Blocks/BlocksExampleTest.php
Add forms as default allowed blocks
=> Add forms as default allowed blocks

CHANGELOG.md, package.json
=> updating change log for new release

.github/workflows/ci.yml, composer.json, phpstan.neon.dist, src/Blocks/AbstractBlocks.php, src/Cli/AbstractCli.php, src/Cli/CliInitProject.php, src/Cli/CliInitTheme.php, src/CustomPostType/LabelGenerator.php, src/Helpers/Components.php, src/Main/AbstractMain.php, src/Main/Autowiring.php, src/Menu/BemMenuWalker.php, tests/Blocks/BlocksExampleTest.php
Updated the composer version and bumped the minimum PHP version to 7.4
Fixed the phpstan issues from the new update
=> Update composer requirements

src/Helpers/Components.php, tests/Datasets/Arguments.php, tests/Helpers/ComponentHelpersTest.php
This a PHP sidekick to [this PR](https://github.com/infinum/eightshift-frontend-libs/pull/575) in Frontend Libs. You can find more info there.
\-
\-
=> Global CSS variables color values output

src/Blocks/AbstractBlocks.php, src/Rest/Fields/FieldCli.php, src/Rest/Routes/RouteCli.php, tests/AdminMenus/AdminMenuExampleTest.php, tests/Helpers/ComponentHelpersTest.php, tests/Rest/Fields/FieldCliTest.php, tests/Rest/Routes/RouteCliTest.php, tests/data/src/Blocks/components/layout/layout-style.scss, tests/data/src/Blocks/components/layout/layout.php, tests/data/src/Blocks/components/layout/manifest.json
=> Fix failing tests

phpunit.xml, src/Blocks/AbstractBlocks.php, src/Blocks/AbstractBlocksCli.php, src/Blocks/BlockVariationCli.php, src/Blocks/BlockWrapperCli.php, src/Cli/AbstractCli.php, src/Cli/CliInitAll.php, src/Cli/CliInitProject.php, src/Cli/CliInitTheme.php, src/Helpers/Components.php, src/Manifest/AbstractManifest.php, src/Setup/UpdateCli.php, tests/Cli/AbstractCliTest.php
The testing constant was named `TEST`, which can be an issue when you are running tests in your project, and have the constant named TEST as well.
In my case, the issue was the path of the manifest file, which was wrong in the tests.
I've prefixed our test constant to `ES_TEST`, which should be ok.
=> Change test variable

src/Blocks/AbstractBlocks.php, src/Exception/InvalidBlock.php, src/Helpers/StoreTrait.php
- added variations to the store.
https://github.com/infinum/eightshift-frontend-libs/pull/630
=> Adding variations to store

src/Blocks/AbstractBlocks.php, src/Exception/ComponentException.php, src/Helpers/Components.php
- new partial helper that will load file from any component/block as a partial in a new folder used for small view components.
=> adding partial helper

.github/workflows/ci.yml
=> Add standards:check Composer script

composer.json, src/Geolocation/AbstractGeolocation.php, src/Geolocation/Readme.md, src/Geolocation/geolocationDetect.php
- New function for providing cookie expiration time.
- New file providing geolocation with WP-Rocket cache
=> Adding geolocation corrections

src/AdminMenus/ReusableBlocksHeaderFooterExample.php
Adds microoptimizations suggested by Denis
=> Reusable header/footer performance optimizations

src/Helpers/CssVariablesTrait.php
- updating random Id generator to output 8 rather than 32 characters.
=> updating random Id generator

CHANGELOG.md, src/Enqueue/Blocks/AbstractEnqueueBlocks.php
- Removed enqueuing dependency for block editor only styles.
=> updating block admin enque

src/Cache/ManifestCacheExample.php, src/Cli/AbstractCli.php
- Wrong file name
- Adding fixes for strauss
=> adding fixes for wrong file name

CHANGELOG.md, src/Geolocation/AbstractGeolocation.php
- Countries get list pulled the data from the wrong manifest cache file.
=> Release 8.0.7

src/InitSetup/tailwind/plugin/tailwind.config.mjs, src/InitSetup/tailwind/theme/tailwind.config.mjs
Should prevent this warning:
\-
\-
=> Default Tailwind config update

CHANGELOG.md, src/Helpers/MediaTrait.php
- Updated `isWebPMediaUsed` method to use static variable so the check is done only once.
=> adding optimizations for webP check

CHANGELOG.md, src/Helpers/StoreBlocksTrait.php, src/Rest/Routes/AbstractRoute.php
- New `getRequestParams` helper to extract params from request based on the request type.
- New `prepareSimpleApiParams` helper to prepare and secure params for simple API endpoints.
- New `checkUserPermission` helper to check user permission for route action.
=> updating route helpers

CHANGELOG.md, src/Helpers/CacheTrait.php
- Manifest cache is not stored in internal cache and transients and auto invalidated if needed. This approach is more efficient and faster and is preparation if you have persistent cache storage.
=> adding transient storage
