CHANGELOG.md
src/class-main.php

Changelog
---
* Added `build_di_container()` method to class Main allowing the container to be used outside of WP environment (for example to inject built objects into test cases)

Add method for fetching DI container

---

src/blocks/class-blocks.php

Added block manifest registration ability to register blocks in different namespace than global settings.
By default all blocks take namespace from global namespace but now you can provide namespace in each block and it will take that as default.
This is in combination with PR on the Eightshift-Frontend-Libs (https://github.com/infinum/eightshift-frontend-libs/pull/84)

Added block manifest registration

---

CHANGELOG.md
src/enqueue/class-assets.php
src/enqueue/class-enqueue-admin.php
src/enqueue/class-enqueue-blocks.php
src/enqueue/class-enqueue-theme.php

I've added an abstract class to avoid repeating the method calls for dependencies. Also, config interface has static methods so the handle names and other config related methods had to be changed into static calls.
This PR should enable people to add additional handlers in their enqueue classes with something like:
```php
use Eightshift_Libs\Enqueue\Enqueue_Admin;
class My_Enqeueue extends Enqueue_Admin {
public function enqueue_scripts() {
parent::enqueue_scripts();
// Enqueue additional scripts?
}
protected function get_admin_script_dependencies() {
return [ 'wp-pointer', 'jquery-ui-sortable' ];
}
protected function get_localizations() {
return [
'randomStuff' => esc_html__( 'Hi!', 'text-domain' );
];
}
}
```
Feel free to test before approving this 😄

Update enqueue functionality

---

CHANGELOG.md
composer.lock
src/blocks/class-blocks.php
src/exception/class-invalid-block.php

* class-blocks.php - Added custom filter `block-attributes-override` to be able to override attributes depending on the post type.
* class-invalid-block.php - Fixed error msg.
Usage:
In project>src>blocks>class-blocks.php add filter
```php
/**
* Register all the hooks
*
* @since 1.0.0
*
* @return void
*/
public function register() {
parent::register();
add_filter( $this->config->get_config( static::BLOCK_ATTRIBUTES_FILTER_NAME ), [ $this, 'override_wrapper' ] );
}
/**
* Override wrapper on all blocks.
*
* @param array $attr Array of blocks details.
* @return array
*/
public function override_wrapper ( $attr ) : array {
$attr['styleBackgroundColor']['default'] = 'black';
return $attr;
}
```

adding block-attributes-override filter

---

CHANGELOG.md
src/enqueue/class-enqueue-admin.php
src/enqueue/class-enqueue-blocks.php
src/enqueue/class-enqueue-theme.php
src/manifest/class-manifest.php

Added `get_config` getter in the manifest class, so the config is exposed from the manifest.
This PR addresses the https://github.com/infinum/eightshift-boilerplate/issues/201 issue.

Removed dependency from the enqueue classes

---

CHANGELOG.md
src/blocks/class-blocks.php

Changelog
---
* Add theme support for editor color pallete.
Should be merged along with (or before) https://github.com/infinum/eightshift-frontend-libs/pull/99

Add editor-color-pallete in libs.

---

CHANGELOG.md
src/blocks/class-blocks.php

Add a way to read colors from manifest inside PHP - for example if you need to define a custom page background color select in ACF. (You still then have a dependancy on `class-blocks.php` ideally these would be exposed as static functions but IMO it's good enough for now).

Add public get colors function

---

phpstan.neon.dist
src/blocks/class-blocks.php
src/class-main.php
src/exception/class-component-exception.php
src/exception/class-failed-to-load-view.php
src/exception/class-invalid-block.php
src/exception/class-invalid-callback.php
src/exception/class-invalid-manifest.php
src/exception/class-invalid-nouns.php
src/exception/class-invalid-service.php
src/exception/class-plugin-activation-failure.php
src/helpers/class-components.php
src/manifest/class-manifest.php
src/menu/class-bem-menu-walker.php
src/menu/class-menu.php

I've had to exclude some checks as they are false positive. Most of the config calls are false-positive because they depend on the `Config_Data` interface, which dictates that those methods have to exist - but they will be implemented in the theme or a plugin, and there are no concrete implementations in the libs, so it says it's an error when it's not.
Walker has core inconsistencies (https://core.trac.wordpress.org/ticket/50261) that are throwing false-positives.
I've made some changes so it would be great if we test this before merging 😬 
Ideally, we'd have automated tests but I need to work on those...

Fix phpstan issues

---

CHANGELOG.md
src/menu/class-bem-menu-walker.php

I've removed the declaration and documentation of db_fields which was causing override of the variable from the parent class.
This will fix the problem of non displaying the submenus at frontend.

Bugfix in BEM menu walker 

---

src/Helpers/Components.php

As @volfkarlo can probably testify, without `trim()`, `Components::render()` might make your life miserable as having a component's PHP part defined as:
```php
?>
<div>...</div>
```
and 
```php
?>
<div>...</div>
```
Is not the same (the first one will leave a newline in output - potentially breaking your layout).

Trim before output

---

src/View/AbstractEscapedView.php

Allowed class, id and type attributes to buttons rendered by `Components::render` while extending `AbstractEscapedView` class
This broke the hamburger and drawer components as hamburger button didn't have class attribute.

Allowed more attributes on buttons

---

src/ThemeOptions/ThemeOptionsExample.php

There was an error while adding the Theme Options class.
The error was caused because of the wrong `THEME_OPTIONS_CAPABILITY` and there was no value inside `acf_add_local_field_group`.
I've changed the capability and added an example placeholder field.

Acf theme options fix

---

src/View/AbstractEscapedView.php

If we output the custom head component, almost everything will be escaped.
Adding meta and link elements to this filter fixes the head component

Allow meta and link to be rendered with wp_kses_post

---

src/Helpers/Shortcode.php

Variable was written in `camelCase`

Fix global varible name for Shortcode class

---

src/ConfigProject/ConfigProjectExample.php

I think we should not have debugging turned on when in production or staging.

Remove debugging if not development setup

---

src/Cli/AbstractCli.php
src/Setup/SetupCli.php
src/Setup/UpdateCli.php
tests/Setup/SetupCliTest.php
tests/Setup/UpdateCliTest.php

This took way more than I hoped it would, ran into some weird issues and path brainf##ks, but all is good now 😄 
Changelog:
- `AbstractCli` wasn't detecting the test environment correctly, added the condition that makes it work now
- extracted command name to a const in `SetupCli` and `UpdateCli`
- added check in `UpdateCli` to detect if we're in a test environment and make it point to `setup.json` in `cliOutput` instead of libs root folder
- added tests for `SetupCli` and `UpdateCli`

Setup tests

---

src/CustomTaxonomy/TaxonomyCli.php
tests/CustomTaxonomy/TaxonomyCliTest.php

When generating a custom taxonomy, the doc comment of the generated file always had
> The Blog_Taxonomy specific functionality.
as a doc comment.
This PR corrects it to include the class name, aka
> The `$className` specific functionality.

Custom taxonomy wrong doc comment fix

---

src/Main/Autowiring.php

Exclude the non-service classes from autowiring.
This should fix the bug I was experiencing on a client's site.
This is a temp fix without tests (we'll add those in 3.1.0).

Fix the autowiring issue

---

src/Main/Autowiring.php

- autowire is now throwing error if you push a primitive as a DI, but it called the main class that used string and array as a DI variables. I ignored them from the check.

updating autowire to ignore main DI

---

src/Helpers/Components.php
tests/Helpers/ComponentHelpersTest.php
tests/data/src/Blocks/components/variables/manifest.json

This fix ensures these kinds of variables are properly handled on front (in PHP).
```json
"typographyUppercase": {
"true": [
{
"variable": {
"typography-uppercase": "uppercase"
}
}
]
},
```

Fix correct boolean handling when outputting css variables

---

src/Cli/CliHelpers.php
src/Helpers/Components.php
tests/Cli/CliHelpersTest.php
tests/Datasets/Arguments.php
tests/Helpers/ComponentHelpersTest.php

Adds a kebab-to-camelCase helper (and a corresponding test) for cases when you need camelCased things (e.g. using the `Blocks::props` with a component that has a `-` in the name).

Kebab-case to camel case helper

---

src/Blocks/BlocksCli.php
src/Blocks/BlocksExample.php
src/CustomPostType/PostTypeCli.php
src/CustomPostType/PostTypeExample.php
src/CustomTaxonomy/TaxonomyExample.php

Changelog
---
* Fix phpstan errors that pop up after certain classes / blocks are generated
* Fix broken setup using latest libs (`release/3.1.0`) / frontend libs (`develop`) because of missing `link` component / block
* Fixed a warning during `wp boilerplate create_post_type` if `menu_position` parameter is not provided
#153, #152 (which this PR was supposed to fix) seem to already be fixed, the text domain is properly set, for example this is one I just created in my test theme (same thing for CPT):
```php
/**
* Get the arguments that configure the custom taxonomy.
*
* @return array Array of arguments.
*/
protected function getTaxonomyArguments(): array
{
return [
'hierarchical' => true,
'label' => \esc_html__('Some Taxonomy', 'boilerplate301'),
'show_ui' => true,
'show_admin_column' => …
```

Minor setup fixes

---

src/Setup/Setup.php

Github plugin install now works with automatically built release zips implemented https://github.com/infinum/eightshift-forms/pull/58.

Change github plugin install path

---

src/Cli/CliInitTheme.php

When using the npx command, the readme gets pulled from the boilerplate, and the setup script fails with readme already exists.

Remove readme command from the setup theme script

---

src/Cli/CliHelpers.php
src/Setup/Setup.php
src/Setup/setup.json
tests/Cli/CliHelpersTest.php
tests/Datasets/Arguments.php
tests/Setup/UpdateCliTest.php

Because of the way `wp plugin install` works with remote zips (it appends a random hash at the end of the file after unzipping) and you can't change the name of the archive, we need to do it like this:
1. Download `release.zip` from a repo and save it as the correct plugin name (for example: `eightshift-forms.zip`)
2. Install from the local file and delete afterwards

Fix plugin install for GitHub plugins

---

src/Helpers/Components.php

Fixed a bug where props would throw a warning if you had a block (let's say `example`) but you don't have an `example` component in your project.

Fix props logic

---

src/Helpers/Components.php

This fixes a bug where some attributes (like wrapper spacing attributes) won't be outputted as CSS variables if they're set to 0.
This is especially problematic if you have something like the following structure in editor:
```
group         // wrapper-spacing-top == 20
heading
paragraph // wrapper-spacing-top == 0
```
Because `paragraph` will inherit the `wrapper-spacing-top: 20` css variable from group block.

Output attributes which can be set as 0

---

src/Helpers/Components.php

Changelog:
- added sort of global breakpoints in output CSS vars function
- corrected output for mobile first
Screenshots:
**What is corrected and how it used to be:**

Fix for responsive variables mobile first

---

src/Helpers/Components.php

Changelog:
- changed condition for bailout
I've noticed that one block couldn't publish only custom CSS variable(translating from wrapper variable to block variable one). So I made these changes.
Use case:
Screenshots:

Set only variables custom

---

.gitattributes
src/AdminMenus/AbstractAdminMenu.php
src/AdminMenus/AbstractAdminSubMenu.php
src/AdminMenus/AdminMenuCli.php
src/AdminMenus/AdminMenuExample.php
src/AdminMenus/AdminSubMenuCli.php
src/AdminMenus/AdminSubMenuExample.php
src/CustomPostType/PostTypeCli.php
tests/AdminMenus/AdminMenuCliTest.php
tests/AdminMenus/AdminMenuExampleTest.php
tests/AdminMenus/AdminSubMenuCliTest.php

The first commit kinda violates the SRP of this PR, but it's a minor addition that helps save the trees.
I've added the templates for generating admin menus and submenus, with an example for usage purposes.
The things that are missing are
I also noticed 2 minor phpstan issues that should be fixed but didn't want to add them here to prevent further pollution of the PR.

Add admin menus cli

---

src/Helpers/Components.php
tests/Helpers/ComponentHelpersTest.php

There's been an issue in a case where you put `"breakpoint": "mobile"` in mobile-first "mode" in responsive or the largest breakpoint in the `inverse: true`, desktop-first responsive "mode".
The issue is resolved by adding default breakpoints recognition. By recognizing the default breakpoint, the breakpoint is reset to value 'default' which allows the variable to be set in a 'default' mode by setting the breakpoint.
Screenshots

Fix for default breakpoints

---

src/Helpers/Components.php

Corrected docs for function default getDefaultBreakpoints.
Sorry for this unnecessary mistake.

Default breakpoints -- docs fix

---

src/Helpers/Components.php

Fixes the errors that pop-up from PHPStand because of `checkAttr()` wild return types. Yes this is slightly less "correct" but it's an easy fix for an otherwise complex problem which we shouldn't spend too much time because it's ultimately irrelevant.

Fix check attr phpstan issues

---

src/Helpers/Components.php

Removes the annoying extra spaces in class string if any of the classes inside the array is empty string (which tends to happen a lot).

Fix extra spaces

---

src/Helpers/Components.php
tests/Helpers/ComponentHelpersTest.php

Changelog:
- added undefined attribute option to checkAttr and checkAttrResponsive helper
Note:
I tried to detect whether the value of a responsive attribute is false or not set(what we need from inheriting) and it turned out I can't distinguish that one with checkAttr nor checkAttrResponsive helpers.
So I figured this could be a reasonable approach. Even though it's technically different from the JS implementation(JS makes difference between `undefined` and `null`). I believe setting parameters to `NULL` makes perfect sense in PHP part.
The reasoning is that in PHP when a variable is unset or not set it is represented as "NULL" if you try to make something with it(even if you check the variable with a function `isset` result is `false`). That's why I believe that setting values to `NULL` …

Added undefined attribute option to checkAttr and checkAttrResponsive helpers

---

src/Helpers/Components.php

When looping through css variables, some values are passed as integers. Using `str_replace()` in internal helper `variablesInner` throws fatal error on integers. Convert it to string when replacing value.

Convert variable to string when replacing value

---

src/Media/MediaExample.php

This PR fixes these issues reported in https://github.com/infinum/eightshift-frontend-libs/issues/491:

A11y improvements

---

.github/workflows/ci.yml
.github/workflows/test.yml

This PR improves the CI/CD workflows in that it will cancel the running builds for the same branch when an update is made (a push to the branch will cancel the previous run so that the new one can start).
This is useful for paid and free actions, as it conserves the minutes spend on CI runs (free is good for the environment, as we're not running unnecessary code and wasting GH's resources, paid is good because we're conserving the GH minutes).
https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/
https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency

CI/CD improvements for GH actions

---

src/View/AbstractEscapedView.php

I couldn't add fill to the SVG so I figured it should be added as standard on our projects.
Changelog:
- add fill property to SVG in abstract escaped view
Example screenshots(`fill: none`):
**Before**
**After**

Add fill property to SVG in AbstractEscapedView class

---

src/Blocks/BlocksCli.php

This PR changes `blocksInit` logic to copy the global manifest file and set up blocks using relevant boilerplate commands instead of the whole block folder, which was causing #267.
Discussed https://github.com/infinum/eightshift-libs/commit/2fcc29d300cf4f3f169ede451c24a22e8d7e2f55 with @iruzevic, and the intended purpose of the change was to copy the global manifest. This didn't work with the `copyRecursively` method as it sets up a `RecursiveDirectoryIterator`, so it expects a path to a folder, not a file.

Fix logic for copying global manifest

---

src/CustomMeta/AbstractAcfMeta.php

- removed ACF is_admin early exit due to not serving ACF fields on the frontend
Note:
This was causing the user image not to be shown on frontend.
@goranalkovic-infinum, @iobrado

Fix for ACF is admin showing fields

---

src/Blocks/AbstractBlocksCli.php
src/Blocks/BlocksCli.php
src/Cli/AbstractCli.php
src/Cli/CliInitAll.php
src/Enqueue/Blocks/AbstractEnqueueBlocks.php
src/Helpers/Components.php
src/Helpers/CssVariablesTrait.php

This PR:
* replaces instances in which `wp boilerplate setup_theme` uses `/` instead of `DIRECTORY_SEPARATOR`
* stops prepending `DIRECTORY_SEPARATOR` to absolute paths on Windows
* this caused `\C:\Users\...` paths on Windows, which were failing
* the Windows check is based upon checking whether `\` is the directory separator, as we only care what's the filesystem structure like 
* stops quoting arguments when calling `wp boilerplate use_block` and `use_component` from `setup_theme`, as this these quotes for some reason aren't stripped on Windows
* I can see that there were some similar bugs in WP-CLI regarding this, but WP-CLI doesn't officially support Windows so I didn't report this additionally
* includes changes from #270 
Using this, I was able to set up a theme (under Windows 11, …

Improve developer experience on Windows

---

src/Blocks/AbstractBlocks.php

Currently when you add 
```php
\add_filter('allowed_block_types_all', [ $this, 'getAllBlocksList' ], 10, 2);
```
All the blocks will be shown (core and es ones).
This PR attempts to fix this.
I'd love it if people could just test this and see if this will affect their projects in any way.

Fix the check that should allow only custom blocks to be added

---

composer.json

Add `lock: false` to composer.json config to prevent composer.lock from creating.
Closes #283

Add lock false to composer json config

---

.gitignore
src/Enqueue/Admin/AbstractEnqueueAdmin.php
src/Enqueue/Blocks/AbstractEnqueueBlocks.php
src/Enqueue/Theme/AbstractEnqueueTheme.php
tests/Datasets/Arguments.php
tests/Enqueue/Admin/EnqueueAdminCliTest.php
tests/Enqueue/Admin/EnqueueAdminExampleTest.php
tests/Enqueue/Blocks/EnqueueBlockExampleTest.php
tests/Enqueue/Theme/EnqueueThemeExampleTest.php
tests/Helpers/SelectorsTraitTest.php

Extract all handles to public methods so that they can be reused if needed.

Exctract handles to public methods

---

src/Blocks/AbstractBlocks.php
tests/Datasets/Arguments.php
tests/Unit/Blocks/BlocksExampleTest.php

- adjusted the getAllBlocksList so that it can be used directly with the allowed_block_types_all filter
- added the main functionality to getAllAllowedBlocksList
- adjust the tests accordingly

Boolean logic allowed blocks -- fix allowed_block_types_all filter callback

---

src/Cli/AbstractCli.php
src/Columns/Taxonomy/AbstractTaxonomyColumns.php
src/Helpers/ObjectHelperTrait.php
src/Main/AbstractMain.php
src/Main/Autowiring.php
src/Menu/AbstractMenu.php
src/Rest/CallableFieldInterface.php
src/Rest/Fields/FieldExample.php
tests/Helpers.php
tests/Unit/Columns/TaxonomyColumnsTest.php

Fixes #281 in all methods in Eightshift Libs, public, private and protected alike.
Note that in AbstractTaxonomyColumns and TaxonomyColumnsTest the variable is renamed to _string as there is no useful documentation about what that parameter is, and no implementation of this method exists in Eightshift Libs, so I can't check what's an appropriate name.
Also note that I have renamed them more aggressively than actually required, e.g. I renamed `$array`, which theoretically isn't reserved as a variable name.
https://www.php.net/manual/en/reserved.keywords.php
https://www.php.net/manual/en/reserved.other-reserved-words.php

Rename method arguments that are using reserved keywords

---

.github/workflows/test.yml
src/Manifest/AbstractManifest.php
tests/Unit/Columns/TaxonomyColumnsTest.php
tests/Unit/Manifest/ManifestExampleTest.php

Fixes conditions for testing in `getAssetsManifestItem`.

Return empty string in tests in getAssetsManifestItem

---

src/Exception/InvalidAutowireDependency.php
src/Main/Autowiring.php
src/Manifest/AbstractManifest.php

- fixing namespace param name for autowiring.
- adding better error msg.

updating fix for php8 param naming

---

src/Helpers/CssVariablesTrait.php
tests/Unit/Helpers/PostTraitTest.php

Fix deprecated string concatenation in CssVariablesTrait (php 8.2 deprecation), and fix the optional parameters before required in the test alias method for the get_the_content function.

PHP issues fixes

---

src/Blocks/AbstractBlocksCli.php
src/Init/InitBlocksCli.php

This PR fixes the issue in #325 
Luckily there were only two files where `esc_html__` was used. In other files, I've left it because those are mostly examples and abstract classes or exception classes.

Remove escaping from cliLog calls

---

src/Geolocation/AbstractGeolocation.php
src/Geolocation/GeolocationExample.php
tests/Unit/Geolocation/AbstractGeolocationTest.php
tests/Unit/Geolocation/GeolocationExampleTest.php

Geolocation wasn't handling errors properly which caused some issues with the tests. Also, I couldn't reproduce the 'headers already sent' errors in the error log, so output buffering was also removed (that caused some minor issues in the tests for me as well).
The tests have been cleaned up a bit (some tests didn't really make sense, and some didn't test the code properly). Not sure if the code coverage was increased or not.
Also fixed the phpcs errors. Not sure how these got merged tbh.

Fix phpcs issues and geolocation errors

---

src/BlockPatterns/BlockPatternCli.php

Fixes wrong WP-CLI command name for generating block patterns. Closes #346

Fix WP-CLI command for generating patterns

---

src/Geolocation/geolocationDetect.php

Removed escaping function `esc_html` which is not needed here and is causing errors.

Remove missing esc_html function from geolocationDetect

---

src/Blocks/UseVariationCli.php
src/Init/InitBlocksCli.php

Changes the default args for init blocks and use block variation CLI commands, as the `button-block` variation will not exist anymore in FE libs v8.0.
\-
\-

CLI commands default block variation update

---

src/Helpers/CssVariablesTrait.php
src/Rest/Routes/LoadMore/LoadMoreRouteExample.php

- you no longer need to add the "blockSsr" attribute when loading a block via server-side rendering. It will automatically utilize global CSS variables and provide the necessary styles.

fixing example

---

src/Blocks/AbstractBlocksCli.php
src/Blocks/UseBlockCli.php
src/Blocks/UseComponentCli.php
src/Blocks/UseVariationCli.php
src/Helpers/Components.php

- added new option to find blocks in the eightshift-frontend-libs-private repo also

adding frontend libs private options

---

CHANGELOG.md
src/Exception/ComponentException.php
src/Helpers/Components.php

- `render` and `renderPartial` methods are now no longer able to call the php files outside of themes/plugin folders. This is a security measure to prevent the execution of arbitrary code.
- `render` method can now call `wrapper` as a component name.

addings render security fixes

---

.github/workflows/integrate.yml
composer.json
phpcs.xml.dist
phpstan.neon.dist
src/Blocks/AbstractBlocksCli.php
src/Blocks/UseAssetsCli.php
src/Blocks/UseGlobalAssetsCli.php
src/Blocks/UseManifestCli.php
src/Blocks/UseStorybookCli.php
src/Db/DbExport.php
src/Db/DbImport.php
src/Init/InitBlocksCli.php
src/Menu/BemMenuWalker.php
src/Readme/README.md
tests/BaseTest.php
tests/Helpers.php
tests/Unit/Blocks/BlocksExampleTest.php
tests/Unit/Cli/CliHelpersTest.php
tests/Unit/Columns/Media/MediaColumnsTest.php
tests/Unit/Exception/ComponentExceptionTest.php
tests/Unit/Exception/FailedToLoadViewTest.php
tests/Unit/Exception/InvalidBlockTest.php
tests/Unit/Exception/InvalidCallbackTest.php
tests/Unit/Exception/InvalidManifestTest.php
tests/Unit/Exception/InvalidServiceTest.php
tests/Unit/Exception/PluginActivationFailureTest.php

This PR will:
- Update coding standards to the latest beta version which should make the libs compatible with PHP 7.4, 8.0, 8.1, 8.2 (and the 8.3 tests seem to be passing)
- Fix the code so that the tests pass (the latest addition of adding private folders broke a lot of tests (95))
- Fix existing issues with phpcs and phpstan 
- I've excluded some errors from phpcs reporting, as they are false positives, mainly the exception ones, as the exception messages are escaped in the exception classes
- Also excluded file creation methods. The WP replacements are not ideal - [wp_mkdir_p()](https://developer.wordpress.org/reference/functions/wp_mkdir_p/) will create directories recursively but with 777 permission, and some other `WP_Filesystem_*` methods are just wrappers with filters added (which …

Update libs with wpcs 3 changes [beta]

---

src/Enqueue/Blocks/AbstractEnqueueBlocks.php

Re-enqueues `lodash` to hopefully make everything work with WP 6.4.

WP 6.4 lodash fix

---

src/Cache/AbstractManifestCache.php
src/Cache/ManifestCacheExample.php

- Version validation for manifest cache

adding additional options for caching

---

CHANGELOG.md
src/Cli/AbstractCli.php
src/Cli/Cli.php
src/Helpers/ObjectHelperTrait.php
src/Init/plugin/.gitignore
src/Init/plugin/phpstan.neon.dist
src/Init/theme/.gitignore
src/Init/theme/phpstan.neon.dist
src/Media/AbstractMedia.php
src/Media/MediaExample.php
src/Optimization/OptimizationCli.php
src/Optimization/OptimizationExample.php

- Media support for svg and json.
- Optimization service class for better performance.
- Phpstan config fix for theme and plugin setup
- Project name variable will now be ucfirst on setup.
- Removed .git folder after the setup.

adding multiple fixes

---

CHANGELOG.md
src/Helpers/AttributesTrait.php

- default attributes render will not throw error if attribute key is missing in component manifest.

Release 8.0.6

---

src/Main/AbstractMain.php

This change allows the function to be called and/or redeclared from extending classes. Prior to this PR, it was set to private:
> Members declared protected can be accessed only within the class itself and by inheriting and parent classes. Members declared as private may only be accessed by the class that defines the member. 
>
> (https://www.php.net/manual/en/language.oop5.visibility.php)
Changes visibility so that I can override `registerServices()` in a project without replacing `getServiceClassesWithDi()`.

Change getServiceClassesWithDi() visibility to protected

---

CHANGELOG.md
src/Helpers/TailwindTrait.php
src/InitSetup/tailwind/plugin/.prettierrc
src/InitSetup/tailwind/plugin/package.json
src/InitSetup/tailwind/theme/.prettierrc
src/InitSetup/tailwind/theme/package.json

- `twClasses` and `twClassesEditor` can now be passed as an array (of strings)
- Fixed a couple of bugs related to Tailwind class output.

Tailwind helpers - updates and fixes

---

CHANGELOG.md
src/ThemeOptions/ThemeOptionsExample.php

- Theme options settings are now saved as string and not as object.

release 9.1.4

---

src/Enqueue/Admin/EnqueueAdminExample.php
src/Enqueue/Blocks/EnqueueBlocksExample.php
src/Enqueue/Theme/EnqueueThemeExample.php

Previously used getProjectName has potential issue if project name consists of more than one word separated with a blank space.

Improve getAssetsPrefix method

---

src/InitSetup/tailwind/theme/404.php
src/InitSetup/tailwind/theme/footer.php
src/InitSetup/tailwind/theme/header.php
src/ThemeOptions/ThemeOptionsExample.php

Fetching newly structured eightshift-theme-options from db needs to be unserialised
e.g.
`$footerPartialId = get_option(ThemeOptions::OPTION_NAME)['footer'] ?? '';`
should look like:
`$footerPartialId = json_decode(get_option(ThemeOptions::OPTION_NAME), true)['footer'] ?? '';`

Fix fetching of ids for partials of provided templates

---

src/Cache/AbstractManifestCache.php
src/InitSetup/standard/plugin/eightshift-boilerplate-plugin.php
src/InitSetup/standard/theme/functions.php
src/InitSetup/tailwind/plugin/eightshift-boilerplate-plugin.php
src/InitSetup/tailwind/theme/functions.php
src/Main/Autowiring.php

Using profiling we've gathered that we spend _a lot_ of time in `Autowiring::buildServiceClasses`. In particular, we spent 14% of the whole page generation time just running the method for `EightshiftForms`.
Here's a screenshot from an Excimer-grabbed profile opened up in Speedscope on my local machine:
I added caching this into a transient using the project namespace as a unique key. This requires transients to be cleared on all deployments, and can cause breakage if `manuallyDefinedDependencies` is changed dynamically at runtime. This should probably be documented in eightshift-docs.
I should probably add a way to toggle this off. Do you prefer `WP_ENVIRONMENT_TYPE`, a special constant or both?
After this change, it's no longer noticeable in the profile and the whole `registerServices` …

Cache Autowiring::buildServiceClasses into a transient

---

src/ClassAttributes/ShouldLoadInCliContext.php
src/Main/AbstractMain.php

Currently, if you want to load a `ServiceInterface`-implementing class in the WP-CLI context, such as a class inheriting from `AbstractPostType` or `AbstractTaxonomy`, you're out of luck. And you really should load those in the CLI context.
Only classes implementing `ServiceCliInterface` are loaded in the CLI context, and they're aren't loaded in the web context. Only classes implementing `ServiceInterface` are loaded in the web context, and you've guessed it.
This could be worked around by just making no such distinction, but that lowers developer flexibility and makes you unable not to load e.g. CLI commands in the web context.
Instead of such compromises, this PR proposes an alternative way to indicate a `ServiceInterface` should be loaded in CLI contexts using a class attribute, a …

Better CLI loading for ServiceInterface implementations

---

src/Helpers/ShortcodeTrait.php

- `getShortcode` content param now fallbacks to empty and not null.

PHP 8.4 fixes
